Use PyPi dependencies for running the scrapers and tests
redhat-exd-rebuilds/estuary-api pull request #303
Opened 2021-04-14 15:58 UTC by mprahl

This also pins the version of neomodel to avoid pulling in pytest
and its dependencies in production. This should be fixed by:
https://github.com/neo4j-contrib/neomodel/pull/553

This will enable the base image to be changed to UBI8.

2021-04-14 16:16 UTC, mprahl commented
The flake8 error will go away after it is rebased on top of #301

2021-04-15 10:34 UTC, apaplaus approved these changes

2021-04-15 10:35 UTC, apaplaus commented
I forgot to change the installation of rpms in other Dockerfiles, so thanks for fixing it.

2021-04-18 18:13 UTC, lioramilbaum commented
I am reviewing the PR although it consists of multiple changes. It is challenging to provide an effective review in a timely manner.

2021-04-18 18:19 UTC, lioramilbaum approved these changes

2021-04-18 18:19 UTC, lioramilbaum commented on README.md
> +The unpinned dependencies are recorded in **setup.py**, and to generate the **requirements.txt** file, run `make pin_dependencies`. This is only necessary when adding a new
It is necessary when requirements.in file is changed: adding/removing a package.

2021-04-18 18:19 UTC, lioramilbaum requested changes
CI is broken

2021-04-19 09:31 UTC, apaplaus commented
> CI is broken

Yes, it's an error cause by flake8. Matt mentioned here(https://github.com/redhat-exd-rebuilds/estuary-api/pull/303#issuecomment-819643068) that the error will be gone after merging on top of his other change.

2021-04-19 09:33 UTC, lioramilbaum commented
> > CI is broken
> 
> Yes, it's an error cause by flake8. Matt mentioned here([#303 (comment)](https://github.com/redhat-exd-rebuilds/estuary-api/pull/303#issuecomment-819643068)) that the error will be gone after merging on top of his other change.

ok. Let's wait then till the other PR is merged and this PR is rebased, before we move on and merge this one.

2021-04-19 18:36 UTC, merged